import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.orivet.com/');
  await page.locator('.w-10').click();
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Email (Username)' }).click();
  await page.getByRole('textbox', { name: 'Email (Username)' }).fill('newuser');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Charlie2017');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Redeem Tests (22)' }).click();
  await page.getByLabel('').nth(5).check();
  await page.getByRole('textbox', { name: 'Barcode Number', exact: true }).click();
  await page.getByRole('textbox', { name: 'Barcode Number', exact: true }).fill('3443456');
  await page.getByRole('textbox', { name: 'Confirm Barcode Number' }).click();
  await page.getByRole('textbox', { name: 'Confirm Barcode Number' }).fill('3443456');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Select Breed' }).click();
  await page.locator('div').filter({ hasText: /^Afghan Hound$/ }).nth(1).click();
  await page.getByRole('textbox', { name: 'Select Animal' }).click();
  await page.getByText('shimi34').click();
  await page.getByText('Intact Female').click();
  await page.getByText('Intact Male').click();
  await page.getByRole('button', { name: '/03/2025' }).click();
  await page.getByRole('button', { name: 'Wednesday, March 5th,' }).click();
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByRole('button', { name: 'Activate Kit' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'We are done' }).click();
});